sudo: required
services: 
- docker
slim: &slim
      stage: Slim
      os: linux
      language: shell
      script:
        - docker build --build-arg MYSQL_VER=$MYSQL_VER -t datajoint/mysql slim/.
        - docker rmi mysql:${MYSQL_VER}
        - docker tag datajoint/mysql:latest datajoint/mysql:${MYSQL_VER}
        - docker tag datajoint/mysql:latest datajoint/mysql:${MYSQL_VER}-slim
        - docker tag datajoint/mysql:latest datajoint/mysql:${MYSQL_VER}-slim-${TRAVIS_COMMIT:0:7}
        - sh -c "[ \"$MYSQL_VER\" = \"5.7\" ] || docker rmi datajoint/mysql:latest"
      after_success:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker images
        - for i in `docker images --format {{.Repository}}:{{.Tag}}`; do docker push $i; done
jobs:
  include:
    - <<: *slim
      env:
      - MYSQL_VER: 5.6
    - <<: *slim
      env:
      - MYSQL_VER: 5.7
    - <<: *slim
      env:
      - MYSQL_VER: 8.0
